### PR TITLE
feat: upgrade to Angular 13 and switch to modern APF

### PR DESCRIPTION
**Pull request by arturovt**
Hey, I've upgraded dependencies to Angular 13. I've also upgraded storybook packages to be compatible with the latest Angular version.

I couldn't run `test` and `test-manual` locally since I'm not familiar with `@ephox/*` packages and how they work.

Angular 13 now exports `.mjs` files and no longer is shipped with UMD bundles; thus, `require('@angular/core')` doesn't work anymore.

`ng-packagr@13` now by default emits Ivy-compatible files since View Engine support has been deprecated and removed. So users who'll use the latest tinymce-angular version will no longer need this package to be handled by the `ngcc` compiler.

### CODE REVIEW

**Comment by jscasca** [comment]
Thanks, this is looking great! Let me take a closer look and run the tests. I haven't familiarised myself with Angular 13 just yet but I hope to merge this soon

**Review by de-dan — APPROVED** [review]
lgtm;
Why are you using rc-versions of storybook?

**Comment by arturovt** [comment]
@de-dan hey. Because storybook@6.4.0 was released 6 days ago, and _rc_ versions were only available when I was making that PR. I'll need to update those packages.

**Review by jscasca — APPROVED** [review]

**Comment by zjxcv7** [comment]
NPM warehouse does not have 5.0 0 version

**Pull request merged**
