### PR TITLE
Allow custom handling of target element by extending the EditorComponent

### PR DESCRIPTION
**Pull request by mpotter-modus**

### CODE REVIEW

**Comment by SimonFc** [comment]
Hi! What event do you need to intercept that can't be handled through TinyMCE? [EventDispatcher](https://www.tiny.cloud/docs/api/tinymce.util/tinymce.util.eventdispatcher/#on)

**Comment by mpotter-modus** [comment]
Hi @SimonFc ! Trying to attach TinyMCE to an existing element rather than have this Angular component create its own element.

**Comment by mpotter-modus** [comment]
So the idea is, by making these 2 props `protected`, you can extend the EditorComponent class and provide a custom/override for `createElement()` that sets `this._element` to an existing element (rather than the `document.createElement()` that's in the repo here).

**Comment by SimonFc** [comment]
The main(maybe only) reason to directly manipulate the DOM directly with Angular is to integrate with third-party libraries, which is what tinymce-angular is doing. Perhaps if what you're trying to do isn't possible to do with this integration it could be a sign that there's something that we could do better! Which makes me wonder, what's the use case for providing an existing element to tinymce-angular?

**Comment by mpotter-modus** [comment]
@SimonFc the use case that led to this PR was to provide a textarea with cols & rows defined on it to set the size of the editor. I've seen that we have width & height "init" options, but those are in pixels. Do you have an alternative suggestion so we can define our size in cols & rows?

**Comment by SimonFc** [comment]
Unfortunately, that wouldn't carry over to TinyMCE once it's instantiated. (This has nothing to do with the integration but is just due to how TinyMCE works). Since an iframe will be created by Tiny there would have to something that can resize that iframe. Also, I suspect that it wouldn't make much sense to have rows and cols with Tiny when you're using elements such as headings and paragraphs, all being of different size :thinking: 

I'll close this PR since what you want to do wouldn't be possible but let me know if you got any questions

**Pull request closed without merging**
