### PR TITLE
perf: remove event listeners when the component gets destroyed and reduce change detection cycles

### PR DESCRIPTION
**Pull request by arturovt**

### CODE REVIEW

**Comment by jscasca** [comment]
@arturovt thanks for this PR. Did you get the CLA email by any chance? we can't merge these changes until you sign the CLA

**Comment by arturovt** [comment]
Hey @jscasca . I've seen that it requires CLA to be signed, but I didn't get any email :(

**Comment by jscasca** [comment]
@arturovt I tried triggering a re-delivery and since the commit points to that same email I hoping you get the CLA email but if you don't let me know and I'll try to chase it from my side

**Comment by arturovt** [comment]
@jscasca I didn't get an email, unfortunately. Also checked the spam folder and it's empty.

**Comment by EkimChau** [comment]
Hi arturovt, we are currently having issues with our CLA system, once its back up you should get an email.  Thank you for your contribution

**Comment by Afraithe** [comment]
I have manually triggered the email send for you, can you check gmail again, and spam folder?

**Comment by arturovt** [comment]
Yeah, I got the email.

**Review by jscasca — APPROVED** [review]

**Review by tiny-james — APPROVED** [review]

**Pull request merged**
