### PR TITLE
Development instructions in README.md updated

### PR DESCRIPTION
**Pull request by tenkmilan**
Added a note to the README.md in the "Development instructions" section for those, who would develop the library on Windows.

### CODE REVIEW

**Comment by fyrkant** [comment]
Thank you for this! But maybe there is a better way to fix this, by updating the build:package script to also work on windows? Maybe by using something like [`copyfiles`](https://www.npmjs.com/package/copyfiles)?

**Comment by tenkmilan** [comment]
Thank you for the feedback! Of course there should be a better, programmatic way. I'm going to take a look at it at the weekend.

**Comment by fyrkant** [comment]
I had some time over so I changed the npm script to use copyfiles instead of cp so it should work in windows now as well. Thank you for bringing this to my attention!

**Comment by tenkmilan** [comment]
You are welcome and thank you for the fix! I just gave it a try and it works fine on Windows as well.

**Pull request closed without merging**
